### ISSUE TITLE
Question: Simple provider usage

### ISSUE THREAD

**Issue by iuslkae** [AzureMarker/shaku#27]
question says.
I want to implement a provider for a component
provider has a function that returns a string
component gets its provider and gets the strings from it.

**Comment by iuslkae** [comment]
How to inject a provider into a component

**Comment by AzureMarker** [comment]
Components cannot have injected providers. Providers provide a single instance of a type (ex. a single string). You probably want to use a component instead. The component would have a function which returns a string.

**Comment by iuslkae** [comment]
@AzureMarker thanks for answer, after some tries and fails, I understood what u said.
Came from angular and nestjs di, thought would be the same but quite different.

**Comment by AzureMarker** [comment]
See also the provider guide: https://docs.rs/shaku/0.6.1/shaku/guide/provider/index.html
