### ISSUE TITLE
actix_web example not working with v4

### ISSUE THREAD

**Issue by iuslkae** [AzureMarker/shaku#28]
![image](https://user-images.githubusercontent.com/50224521/126882396-008350f4-18b4-4f6c-91ac-f8d525076e5d.png)

Example with actix_web 
```
actix-web = {git = "https://github.com/actix/actix-web", tag = "web-v4.0.0-beta.8"}
```
forked, then update the dependency to this version then ...

**Comment by AzureMarker** [comment]
Actix v4 is a breaking change from v3, so v3 code is not expected to compile with v4. The example code will be updated after Actix v4 is released (and `shaku_actix` is updated).

**Comment by iuslkae** [comment]
@AzureMarker thanks for the example don't know how, but i copied the chunk in my source, then it works without change ;')
