### ISSUE TITLE
Building modules on demand, e.g. in a request

### ISSUE THREAD

**Issue by clemens-msupply** [AzureMarker/shaku#32]
We have the use-case where we like to instantiate multiple services that should all use the same database transaction in a single request.

One option would be to have a DBTransactionModule that has a TxComponent which starts/stops a tx when created/dropped and is passed to all services. DBTransactionModule is then created/dropped for every request. Would this be possible? e.g. is it cheap to build a new module in every request?

**Comment by AzureMarker** [comment]
You're probably looking for [Providers](https://docs.rs/shaku/0.6.1/shaku/guide/provider/index.html). That link includes an example that should be similar to your use case (per-request database connection/transaction).

I wouldn't really recommend creating a new module for every request, although depending on your component implementations it might be cheap enough. Creating a module is mostly just initializing all of the components in order of dependency and storing them in the module. Now that I think through it, a per-request module might be a valid solution, but it's at least not an intended use case.

**Comment by clemens-msupply** [comment]
Yes I was looking at providers but I want to do something like this:

```Rust
let tx = ConnectionWithTx::new();
// service1 and service2 use the same transaction:
let service1 = Service1::new(tx.clone());
let service2 = Service2::new(tx.clone());
```

As I understand a provider would create two connections, one for Service1 and one for Service2, or did I miss something?

**Comment by AzureMarker** [comment]
Yeah, you should probably try having a module per request then. If you do need any longer-living components, you could reference them through the submodule feature (one long living module used by short living modules):
https://docs.rs/shaku/0.6.1/shaku/guide/submodules/index.html

**Comment by clemens-msupply** [comment]
Thanks, you could probably also use submodules to avoid initializing modules for every requests? i.e. only the the connection module is initialized on every request and the rest is reused:

``` rust
module! {
    ServiceModuleImpl: ServiceModule {
        components = [],
        providers = [Service1Impl, Service2Impl]
    }
}

module! {
    RootModule {
        components = [ConnectionManagerImpl],
        providers = [],

        use ServiceModule {
            components = [],
            providers = [Service1, Service2]
        }
    }
}

// create root module on every request:
fn request() {
    let root_module = RootModule::builder(cached_service_module).build();
    ...
}
```

**Comment by AzureMarker** [comment]
Yeah, that's what I meant by the submodule reference. Let me know if something doesn't work out though!
