### ISSUE TITLE
Still being developed ?

### ISSUE THREAD

**Issue by iangregsondev** [AzureMarker/shaku#35]
Hi,

Been on the lookout for a dependency injection library, most seem unfinished or abandoned.

I was hoping that this is still in development ?

Could you let me know

Thanks in advance.

**Comment by AzureMarker** [comment]
I have a section in the readme about project status, copying it here:

> The foundation of shaku's API is in place, and now the focus is to mature the project based on user feedback. I (@AzureMarker) am active in the project, but I do not have many major changes of my own planned for the future. Most of the future changes will be based on user feedback.

**Comment by iangregsondev** [comment]
Ah thank you, sorry, I missed that.

I am going to have a play then.

Regards
