### ISSUE TITLE
inject with vector 

### ISSUE THREAD

**Issue by ItsFunny** [AzureMarker/shaku#36]
```rust
#[derive(Component)]
#[shaku(interface = DateLogger)]
struct DateLoggerImpl {
    #[shaku(inject)]
    logger: Vec<Arc<dyn Logger>>,
    today: String,
    year: usize,
}
```

Seems It will be failed for "Found non-Arc type annotated with #[shaku(inject)]"

Edit (@AzureMarker): improved code readability

**Comment by AzureMarker** [comment]
`Vec` is not `Arc`. The top level type must be `Arc`. What are you trying to do with `Vec`?

**Comment by ItsFunny** [comment]
> `Vec` is not `Arc`. The top level type must be `Arc`. What are you trying to do with `Vec`?

Sorry, It is my bad , 
All I want to do is : I want to inject multiple implementation, (for example: trait Logger has  multi implementations)
And They are all wrapped by DateLoggerImpl

**Comment by AzureMarker** [comment]
You can only use one implementation of a trait, so it only makes sense to have one logger in the struct. The idea is to not care about the implementation, only the interface, so you shouldn't depend upon anything outside of the interface (i.e. the implementation).

**Comment by ItsFunny** [comment]
Okay, Close

**Comment by mido0258** [comment]
Have prepared this feature will be going for review today
