### ISSUE TITLE
Integration with config crate

### ISSUE THREAD

**Issue by ctlrcasara** [AzureMarker/shaku#39]
Integration with [config](https://crates.io/crates/config) crate like crate [waiter](https://crates.io/crates/waiter_di): https://github.com/dmitryb-dev/waiter#properties.

**Comment by AzureMarker** [comment]
You can pass in the resolved property values with https://docs.rs/shaku/latest/shaku/struct.ModuleBuilder.html#method.with_component_parameters. I don't intend on adding a dependency for deep `config` integration at the moment.

**Comment by acelot** [comment]
I want to reopen this issue, but I'm offer another approach. `config` crate relies on `serde` deserialize trait. Let's see my example:

```rust
// App, Jwt and Redis are simple structs with no behavior.

pub trait Config: Interface {
    fn app(&self) -> &App;
    fn jwt(&self) -> &Jwt;
    fn redis(&self) -> &Redis;
}

#[derive(Component, Deserialize)]
#[shaku(interface = Config)]
pub struct ConfigImpl {
    pub app: App,
    pub redis: Redis,
    pub jwt: Jwt,
}

impl Config for ConfigImpl {
    fn app(&self) -> &app::App {
        &self.app
    }

    fn jwt(&self) -> &jwt::Jwt {
        &self.jwt
    }

    fn redis(&self) -> &redis::Redis {
        &self.redis
    }
}

module! {
    pub ConfigModule {
        components = [ConfigImpl],
        providers = []
    }
}
```

Initialization function:
```rust
pub fn init_module() -> ConfigModule {
    let config = config_crate::Config::builder()
        .add_source(config_crate::File::with_name("config/default"))
        .build()
        .unwrap()
        .try_deserialize::<ConfigImpl>()
        .unwrap();

    ConfigModule::builder()
        .with_component_parameters::<ConfigImpl>(ConfigImplParameters {
            app: config.app,
            jwt: config.jwt,
            redis: config.redis,
        })
        .build()
}
```

As you can see I need to map all fields from `ConfigImpl` to `ConfigImplParameters` to create a module.
Let me suggest two ways to remove this mapping:
1. Pass all derives from Impl to ImplParameters, then I can deserialize config using `ConfigImplParameters` directly.
2. Allow to `Component`-derive to generate `impl From<ConfigImpl> for ConfigImplParameters`, then I can call `.with_component_parameters::<ConfigImpl>(config.into())`

**Comment by acelot** [comment]
@AzureMarker sorry for mentioning, what do you think?

**Comment by AzureMarker** [comment]
This can still be done without adding an integration. Add a `config: Config` field in the component, create it via the config library of your choice outside shaku, and pass it via parameters: `MyComponentParameters { config }`.

If you want to share the config struct, you could wrap it in an Arc or other no-lifetimes reference sharing type.

**Comment by acelot** [comment]
Thanks for the idea, i'll do that! 👍
