### ISSUE TITLE
Async trait support?

### ISSUE THREAD

**Issue by pleshevskiy** [AzureMarker/shaku#41]
Some time ago Rust (nightly) started to support asynchronous trait, but unfortunately this library is not able to work with such trait. Do you plan to add support? Perhaps under the nightly feature?

**Comment by pleshevskiy** [comment]
But with `async-trait` crate it works as expected... maybe it upstream issue

**Comment by pleshevskiy** [comment]
How can I resolve the asynchronous connection to the database? For example via bb8 crate

https://docs.rs/shaku/latest/shaku/guide/provider/index.html#manually-implement-provider

**Comment by AzureMarker** [comment]
You can have it return the future instead of the connection itself.

**Comment by pleshevskiy** [comment]
Thanks! I'll try.
