### ISSUE TITLE
Allow to manually create `InjectProvided` structs 

### ISSUE THREAD

**Issue by jontze** [AzureMarker/shaku#44]
Thanks for the cool project, I just started to use it recently in combination with `axum` and really love it! :heart: 

So I also installed and used the `shaku_axum` integration. While writing unit test for routes, I encountered one interesting limitation. I could not find any examples or other people that seem to encounter this problem, so it might be that I just have overseen the better / correct approach to do this. However, here my use case:

**Problem Description:**

I have a axum router that injects a provider of a module.
```rust

pub async fn create_user(
    manager: InjectProvided<CoreModule, dyn Manager>,
    Json(webhook_payload): Json<RegisterWebhookPayload>,
) -> Result<Json<RegisterWebhookResponse>, StatusCode> {
   unimplemented!("Call a method of the injected provider");
}

```

Now I want to unit test this router by passing a provider struct that implements a modified version of the `Manager` trait (e.g. by using the `mockall` crate) to the function as parameter. But I'm unable to manually create an instance of the `InjectProvided` tuple Struct as the fields are both private:
```rust
// Compiler error

#[tokio::test]
    async fn test_router_example() {
        let mut fake_provider = MockFakeProvider::new();

        let faked_injectable: InjectProvided<CoreModule, (dyn base::manager::Manager + 'static)> =
            InjectProvided(Box::new(fake_provider), PhantomData);  // <---- This throws

        // Throws the following error:
        //     error[E0423]: cannot initialize a tuple struct which contains private fields
        //     --> api/src/lib.rs:132:13
        //     |
        // 132 |             InjectProvided(Box::new(fake_provider), PhantomData);
        //     |             ^^^^^^^^^^^^^^
        //     |
        //      note: constructor is not visible here due to private fields
        //     --> /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/shaku_axum-0.4.0/src/inject_provided.rs:79:5
        //     |
        // 79  |     Box<I>,
        //     |     ^^^^^^ private field
        // 80  |     PhantomData<M>,
        //     |     ^^^^^^^^^^^^^^ private field

        let result =
            create_user(faked_injectable, Json(RegisterWebhookPayload { id: "123" })).await;
    }
``` 

**Possible Solutions**
1. My first approach was to just make the fields of the `InjectProvided` struct public and it worked.
2. Another approach, that also did the job was to implement a `new` constructor for the struct. So we can create a new instance, while keeping the fields private.

https://github.com/AzureMarker/shaku/blob/20a2efd29277e50576da6755b3f9fc16f40611ef/shaku_axum/src/inject_provided.rs#L78

However, I'm not sure if this is an interaction that should be possible at all for users of the library. Since I only stumbled over this while writing test and basically tried to trick the API a little bit and I'm not that familiar with shaku yet. I also tried to pass the axum state or directly the core module to the router, but this obviously wasn't accepted as the router parameter expect an `InjectProvided` type.

The integrations for `rocket` and `actix` and the `Inject` struct should have the same issue - I didn't tested it for these though. 

I would love to hear your thoughts about this!

**Comment by AzureMarker** [comment]
Luckily there's a simple solution to this: don't directly depend on `InjectProvided` in your business logic.

```rust
fn create_user_impl(manager: &dyn Manager, webhook_payload: RegisterWebhookPayload) -> RegisterWebhookResponse
```

**Comment by jontze** [comment]
Thanks for your quick response on this!

You're right, indeed it was way easier to test when abstracting `InjectProvided` away and encapsulating the business logic from the route handler.
