### ISSUE TITLE
A way to import submodules?

### ISSUE THREAD

**Issue by numfin** [AzureMarker/shaku#45]
First of all thanks for great crate.

I want to use submodules, but the only way in guide is declare them in 1 place.
Is it possible to add functionality to "import" submodules?

I think about:
```rust
module! {
    RootModule {
        components: [],
        providers: [],
        imports: [Module1, Module2],
        exports: []
    }
}

module! {
    Module1 {
        components: [],
        providers: [Module1Provider],
        imports: [],
        exports: [Module1Provider]
    }
}

module! {
    Module2 {
        components: [],
        providers: [],
        imports: [Module1], // We don't need to specify what we need from module1, provide everything that exported from module1
        exports: [Module2Provider]
    }
}
```

**Comment by AzureMarker** [comment]
It doesn't really work out with the type system. There's the possibility of conflicting impls when you say something like "implement MyTrait for X for all implementations of MyTrait on Y and Z". Take a look at what the `module` macro expands to (such as with `cargo-expand`), and try to fiddle around with it, maybe I'm wrong.

You're using some odd syntax in your example, so I'm not exactly sure what the scenario is. Can you share a real code example that shows the issue?

Does this help? It shows how you can depend on modules while only importing the things you need from it (e.g. not importing dependencies that are only used internally in the module - `MyComponent` in this case). It also shows how you can import and "export" components/providers using module traits (`HasComponent`/`HasProvider`).
```rust
use shaku::{HasComponent, HasProvider, Interface};
use shaku_derive::{module, Component, Provider};
use std::sync::Arc;

trait MyComponent: Interface {}
trait MyProvider {}

trait Module1: HasComponent<dyn MyComponent> {}
trait Module2: HasProvider<dyn MyProvider> {}

#[derive(Component)]
#[shaku(interface = MyComponent)]
struct MyComponentImpl;
impl MyComponent for MyComponentImpl {}

#[derive(Provider)]
#[shaku(interface = MyProvider)]
struct MyProviderImpl {
    #[shaku(inject)]
    #[allow(dead_code)]
    component: Arc<dyn MyComponent>,
}
impl MyProvider for MyProviderImpl {}

module! {
    Module1Impl {
        components = [MyComponentImpl],
        providers = []
    }
}

module! {
    Module2Impl {
        components = [],
        providers = [MyProviderImpl],

        use Module1 {
            components = [MyComponent],
            providers = []
        }
    }
}

module! {
    RootModule {
        components = [],
        providers = [],

        use Module2 {
            components = [],
            providers = [MyProvider]
        }
    }
}
```
