### ISSUE TITLE
Component with trait containing async fn

### ISSUE THREAD

**Issue by samuelint** [AzureMarker/shaku#50]
Hi!

I have the error 
```
the trait `SQliteConnectionFactory` cannot be made into an object
consider moving `get` to another trait
only type `infrastructure::database::sqlite_connection_factory::SQliteConnectionFactoryImpl` implements the trait, consider using it directly instead
```

with the following code:

```
use std::error::Error;

use super::migrator::migrate_database;

use sea_orm::{Database, DatabaseConnection};
use shaku::Component;

use shaku::Interface;

pub trait SQliteConnectionFactory: Interface {
    async fn get(&self) -> Result<DatabaseConnection, Box<dyn Error>>;
}

#[derive(Component)]
#[shaku(interface = SQliteConnectionFactory)]
pub struct SQliteConnectionFactoryImpl {
    #[shaku(default)]
    database_url: String,
}

impl SQliteConnectionFactory for SQliteConnectionFactoryImpl {
    async fn get(&self) -> Result<DatabaseConnection, Box<dyn Error>> {
        let db = Database::connect(self.database_url.as_str()).await?;

        migrate_database(&db);

        Ok(db)
    }
}

impl SQliteConnectionFactoryImpl {
    pub fn new(database_url: String) -> Self {
        Self { database_url }
    }
}

```

if I remove the async from the trait (and impl) the error disappears.

What is the catch? How to have a `Component` (singleton) with a async function in trait?

Thanks!

**Comment by samuelint** [comment]
I'll provide the answer here so others with the same issue can find the solution.

The async keyword is not currently supported on traits in the latest stable version of Rust. To work around this, you can use the async-trait crate:
https://github.com/dtolnay/async-trait

**Comment by Sajjon** [comment]
@samuelint async fn has been supported for 13 months on Stable - dee announcement from dec 2023:

https://blog.rust-lang.org/2023/12/21/async-fn-rpit-in-traits.html

So does skahus derive macro support async fn now?

**Comment by AzureMarker** [comment]
@Sajjon Shaku does not explicitly block async methods in traits. The issue is that the current async fn in traits implementation is not object safe:
> Dynamic dispatch
>
> Traits that use -> impl Trait and async fn are not object-safe, which means they lack support for dynamic dispatch.

You can work around this with the `async_trait` library, for example.
