### ISSUE TITLE
Automatic building from modules

### ISSUE THREAD

**Issue by DenuxPlays** [AzureMarker/shaku#51]
The `modules!` macro could be replaced with an attribute.
Also attributes can be moved into attributes.
it could look something like this:
```rs
#[derive(Component)]
#[shaku(#
  interface = DateLogger),
  module = "MyModule"
]
struct DateLoggerImpl {
    #[shaku(inject)]
    logger: Arc<dyn Logger>,
    #[shaku(default = (module = "MyModule", value = "Jan 26"))
    today: String,
    #[shaku(default = (value = "Jan 26"))
    year: usize,
}
```
The second `default` would apply to all modules listed above.
The fully build module can be generated as a Lazy in the main.rs file.

This would basically remove the need to declare anything in the main function.

How do I find this idea?

**Comment by AzureMarker** [comment]
I'm not sure the example makes sense. A module brings together many components and providers, it doesn't have injected fields of it's own.

I'm not looking to drastically change the API right now.

**Comment by DenuxPlays** [comment]
Sounds fair
